sudo: required
services:
  - docker

before_install:
  - docker build -t jongschneider/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run jongschneider/complex npm test -- --coverage

after_success:
  - docker build -t jongschneider/complex-client ./client
  - docker build -t jongschneider/complex-nginx ./nginx
  - docker build -t jongschneider/complex-server ./server
  - docker build -t jongschneider/complex-worker ./worker
  # Login to the Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take these images and push them to Dockerhub
  - docker push jongschneider/complex-client
  - docker push jongschneider/complex-nginx
  - docker push jongschneider/complex-server
  - docker push jongschneider/complex-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-155763739380
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
